//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class StrTableCollection : global::System.IDisposable, global::System.Collections.IEnumerable
    , global::System.Collections.Generic.IEnumerable<StrTable>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal StrTableCollection(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(StrTableCollection obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~StrTableCollection() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TreeizeRelDPINVOKE.delete_StrTableCollection(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public StrTableCollection(global::System.Collections.ICollection c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (StrTable element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public StrTable this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(StrTable[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(StrTable[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, StrTable[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  global::System.Collections.Generic.IEnumerator<StrTable> global::System.Collections.Generic.IEnumerable<StrTable>.GetEnumerator() {
    return new StrTableCollectionEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new StrTableCollectionEnumerator(this);
  }

  public StrTableCollectionEnumerator GetEnumerator() {
    return new StrTableCollectionEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class StrTableCollectionEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<StrTable>
  {
    private StrTableCollection collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public StrTableCollectionEnumerator(StrTableCollection collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public StrTable Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (StrTable)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    TreeizeRelDPINVOKE.StrTableCollection_Clear(swigCPtr);
  }

  public void Add(StrTable x) {
    TreeizeRelDPINVOKE.StrTableCollection_Add(swigCPtr, StrTable.getCPtr(x));
    if (TreeizeRelDPINVOKE.SWIGPendingException.Pending) throw TreeizeRelDPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = TreeizeRelDPINVOKE.StrTableCollection_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = TreeizeRelDPINVOKE.StrTableCollection_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    TreeizeRelDPINVOKE.StrTableCollection_reserve(swigCPtr, n);
  }

  public StrTableCollection() : this(TreeizeRelDPINVOKE.new_StrTableCollection__SWIG_0(), true) {
  }

  public StrTableCollection(StrTableCollection other) : this(TreeizeRelDPINVOKE.new_StrTableCollection__SWIG_1(StrTableCollection.getCPtr(other)), true) {
    if (TreeizeRelDPINVOKE.SWIGPendingException.Pending) throw TreeizeRelDPINVOKE.SWIGPendingException.Retrieve();
  }

  public StrTableCollection(int capacity) : this(TreeizeRelDPINVOKE.new_StrTableCollection__SWIG_2(capacity), true) {
    if (TreeizeRelDPINVOKE.SWIGPendingException.Pending) throw TreeizeRelDPINVOKE.SWIGPendingException.Retrieve();
  }

  private StrTable getitemcopy(int index) {
    StrTable ret = new StrTable(TreeizeRelDPINVOKE.StrTableCollection_getitemcopy(swigCPtr, index), true);
    if (TreeizeRelDPINVOKE.SWIGPendingException.Pending) throw TreeizeRelDPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private StrTable getitem(int index) {
    StrTable ret = new StrTable(TreeizeRelDPINVOKE.StrTableCollection_getitem(swigCPtr, index), false);
    if (TreeizeRelDPINVOKE.SWIGPendingException.Pending) throw TreeizeRelDPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, StrTable val) {
    TreeizeRelDPINVOKE.StrTableCollection_setitem(swigCPtr, index, StrTable.getCPtr(val));
    if (TreeizeRelDPINVOKE.SWIGPendingException.Pending) throw TreeizeRelDPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(StrTableCollection values) {
    TreeizeRelDPINVOKE.StrTableCollection_AddRange(swigCPtr, StrTableCollection.getCPtr(values));
    if (TreeizeRelDPINVOKE.SWIGPendingException.Pending) throw TreeizeRelDPINVOKE.SWIGPendingException.Retrieve();
  }

  public StrTableCollection GetRange(int index, int count) {
    global::System.IntPtr cPtr = TreeizeRelDPINVOKE.StrTableCollection_GetRange(swigCPtr, index, count);
    StrTableCollection ret = (cPtr == global::System.IntPtr.Zero) ? null : new StrTableCollection(cPtr, true);
    if (TreeizeRelDPINVOKE.SWIGPendingException.Pending) throw TreeizeRelDPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, StrTable x) {
    TreeizeRelDPINVOKE.StrTableCollection_Insert(swigCPtr, index, StrTable.getCPtr(x));
    if (TreeizeRelDPINVOKE.SWIGPendingException.Pending) throw TreeizeRelDPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, StrTableCollection values) {
    TreeizeRelDPINVOKE.StrTableCollection_InsertRange(swigCPtr, index, StrTableCollection.getCPtr(values));
    if (TreeizeRelDPINVOKE.SWIGPendingException.Pending) throw TreeizeRelDPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    TreeizeRelDPINVOKE.StrTableCollection_RemoveAt(swigCPtr, index);
    if (TreeizeRelDPINVOKE.SWIGPendingException.Pending) throw TreeizeRelDPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    TreeizeRelDPINVOKE.StrTableCollection_RemoveRange(swigCPtr, index, count);
    if (TreeizeRelDPINVOKE.SWIGPendingException.Pending) throw TreeizeRelDPINVOKE.SWIGPendingException.Retrieve();
  }

  public static StrTableCollection Repeat(StrTable value, int count) {
    global::System.IntPtr cPtr = TreeizeRelDPINVOKE.StrTableCollection_Repeat(StrTable.getCPtr(value), count);
    StrTableCollection ret = (cPtr == global::System.IntPtr.Zero) ? null : new StrTableCollection(cPtr, true);
    if (TreeizeRelDPINVOKE.SWIGPendingException.Pending) throw TreeizeRelDPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    TreeizeRelDPINVOKE.StrTableCollection_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    TreeizeRelDPINVOKE.StrTableCollection_Reverse__SWIG_1(swigCPtr, index, count);
    if (TreeizeRelDPINVOKE.SWIGPendingException.Pending) throw TreeizeRelDPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, StrTableCollection values) {
    TreeizeRelDPINVOKE.StrTableCollection_SetRange(swigCPtr, index, StrTableCollection.getCPtr(values));
    if (TreeizeRelDPINVOKE.SWIGPendingException.Pending) throw TreeizeRelDPINVOKE.SWIGPendingException.Retrieve();
  }

}
