//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class StrTable : global::System.IDisposable, global::System.Collections.IEnumerable
    , global::System.Collections.Generic.IEnumerable<StrVector>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal StrTable(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(StrTable obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~StrTable() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TreeizeSwigPINVOKE.delete_StrTable(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public StrTable(global::System.Collections.ICollection c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (StrVector element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public StrVector this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(StrVector[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(StrVector[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, StrVector[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  global::System.Collections.Generic.IEnumerator<StrVector> global::System.Collections.Generic.IEnumerable<StrVector>.GetEnumerator() {
    return new StrTableEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new StrTableEnumerator(this);
  }

  public StrTableEnumerator GetEnumerator() {
    return new StrTableEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class StrTableEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<StrVector>
  {
    private StrTable collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public StrTableEnumerator(StrTable collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public StrVector Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (StrVector)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    TreeizeSwigPINVOKE.StrTable_Clear(swigCPtr);
  }

  public void Add(StrVector x) {
    TreeizeSwigPINVOKE.StrTable_Add(swigCPtr, StrVector.getCPtr(x));
    if (TreeizeSwigPINVOKE.SWIGPendingException.Pending) throw TreeizeSwigPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = TreeizeSwigPINVOKE.StrTable_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = TreeizeSwigPINVOKE.StrTable_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    TreeizeSwigPINVOKE.StrTable_reserve(swigCPtr, n);
  }

  public StrTable() : this(TreeizeSwigPINVOKE.new_StrTable__SWIG_0(), true) {
  }

  public StrTable(StrTable other) : this(TreeizeSwigPINVOKE.new_StrTable__SWIG_1(StrTable.getCPtr(other)), true) {
    if (TreeizeSwigPINVOKE.SWIGPendingException.Pending) throw TreeizeSwigPINVOKE.SWIGPendingException.Retrieve();
  }

  public StrTable(int capacity) : this(TreeizeSwigPINVOKE.new_StrTable__SWIG_2(capacity), true) {
    if (TreeizeSwigPINVOKE.SWIGPendingException.Pending) throw TreeizeSwigPINVOKE.SWIGPendingException.Retrieve();
  }

  private StrVector getitemcopy(int index) {
    StrVector ret = new StrVector(TreeizeSwigPINVOKE.StrTable_getitemcopy(swigCPtr, index), true);
    if (TreeizeSwigPINVOKE.SWIGPendingException.Pending) throw TreeizeSwigPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private StrVector getitem(int index) {
    StrVector ret = new StrVector(TreeizeSwigPINVOKE.StrTable_getitem(swigCPtr, index), false);
    if (TreeizeSwigPINVOKE.SWIGPendingException.Pending) throw TreeizeSwigPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, StrVector val) {
    TreeizeSwigPINVOKE.StrTable_setitem(swigCPtr, index, StrVector.getCPtr(val));
    if (TreeizeSwigPINVOKE.SWIGPendingException.Pending) throw TreeizeSwigPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(StrTable values) {
    TreeizeSwigPINVOKE.StrTable_AddRange(swigCPtr, StrTable.getCPtr(values));
    if (TreeizeSwigPINVOKE.SWIGPendingException.Pending) throw TreeizeSwigPINVOKE.SWIGPendingException.Retrieve();
  }

  public StrTable GetRange(int index, int count) {
    global::System.IntPtr cPtr = TreeizeSwigPINVOKE.StrTable_GetRange(swigCPtr, index, count);
    StrTable ret = (cPtr == global::System.IntPtr.Zero) ? null : new StrTable(cPtr, true);
    if (TreeizeSwigPINVOKE.SWIGPendingException.Pending) throw TreeizeSwigPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, StrVector x) {
    TreeizeSwigPINVOKE.StrTable_Insert(swigCPtr, index, StrVector.getCPtr(x));
    if (TreeizeSwigPINVOKE.SWIGPendingException.Pending) throw TreeizeSwigPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, StrTable values) {
    TreeizeSwigPINVOKE.StrTable_InsertRange(swigCPtr, index, StrTable.getCPtr(values));
    if (TreeizeSwigPINVOKE.SWIGPendingException.Pending) throw TreeizeSwigPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    TreeizeSwigPINVOKE.StrTable_RemoveAt(swigCPtr, index);
    if (TreeizeSwigPINVOKE.SWIGPendingException.Pending) throw TreeizeSwigPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    TreeizeSwigPINVOKE.StrTable_RemoveRange(swigCPtr, index, count);
    if (TreeizeSwigPINVOKE.SWIGPendingException.Pending) throw TreeizeSwigPINVOKE.SWIGPendingException.Retrieve();
  }

  public static StrTable Repeat(StrVector value, int count) {
    global::System.IntPtr cPtr = TreeizeSwigPINVOKE.StrTable_Repeat(StrVector.getCPtr(value), count);
    StrTable ret = (cPtr == global::System.IntPtr.Zero) ? null : new StrTable(cPtr, true);
    if (TreeizeSwigPINVOKE.SWIGPendingException.Pending) throw TreeizeSwigPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    TreeizeSwigPINVOKE.StrTable_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    TreeizeSwigPINVOKE.StrTable_Reverse__SWIG_1(swigCPtr, index, count);
    if (TreeizeSwigPINVOKE.SWIGPendingException.Pending) throw TreeizeSwigPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, StrTable values) {
    TreeizeSwigPINVOKE.StrTable_SetRange(swigCPtr, index, StrTable.getCPtr(values));
    if (TreeizeSwigPINVOKE.SWIGPendingException.Pending) throw TreeizeSwigPINVOKE.SWIGPendingException.Retrieve();
  }

}
