//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class TreeizeRelD {
  public static string writeTreeAndCreateXML(StrTable control, StrTableCollection data) {
    string ret = TreeizeRelDPINVOKE.writeTreeAndCreateXML(StrTable.getCPtr(control), StrTableCollection.getCPtr(data));
    if (TreeizeRelDPINVOKE.SWIGPendingException.Pending) throw TreeizeRelDPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string writeTreeAndCreateJSON(StrTable control, StrTableCollection data) {
    string ret = TreeizeRelDPINVOKE.writeTreeAndCreateJSON(StrTable.getCPtr(control), StrTableCollection.getCPtr(data));
    if (TreeizeRelDPINVOKE.SWIGPendingException.Pending) throw TreeizeRelDPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
