//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class TreeizeSwig {
  public static string writeTreeAndCreateXML(StrTable control, SWIGTYPE_p_std__vectorT_std__vectorT_std__vectorT_std__string_t_t_t data) {
    string ret = TreeizeSwigPINVOKE.writeTreeAndCreateXML(StrTable.getCPtr(control), SWIGTYPE_p_std__vectorT_std__vectorT_std__vectorT_std__string_t_t_t.getCPtr(data));
    if (TreeizeSwigPINVOKE.SWIGPendingException.Pending) throw TreeizeSwigPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string writeTreeAndCreateJSON(StrTable control, SWIGTYPE_p_std__vectorT_std__vectorT_std__vectorT_std__string_t_t_t data) {
    string ret = TreeizeSwigPINVOKE.writeTreeAndCreateJSON(StrTable.getCPtr(control), SWIGTYPE_p_std__vectorT_std__vectorT_std__vectorT_std__string_t_t_t.getCPtr(data));
    if (TreeizeSwigPINVOKE.SWIGPendingException.Pending) throw TreeizeSwigPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
